### ISSUE TITLE
Authentication Feature

### ISSUE THREAD

**Issue by nmosman** [IlmConnect/IlmConnect#3]
Add authentication to both the backend and frontend, and create basic sign-in and register pages

1. Add email/password to User model
2. Allow users to be created through an endpoint (make sure to bcrypt passwords! pull key + salt from config)
3. Allow users to sign in through an endpoint and return a JWT (use a library, pull key from config). Make sure to add an expiration to the JWT (7 days?)
4. Store the JWT on the frontend (local storage?) and pull/use it when the frontend is loaded
5. Create basic sign-up and login pages
6. Create an endpoint where a user can refresh a token using their current token (they'll get back a new token with new expiration date)

**Comment by Aelbannan** [comment]
Will be done today
